apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-5
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions, Sentry, AWS Lambda.
  annotations:
    github.com/project-slug: xantier/sample-service
    sentry.io/project-slug: sample-service
    aws.com/lambda-function-name: HelloWorld
    aws.com/lambda-region: eu-west-1
    jira/project-key: TEST
    snyk.io/org-name: roadie
    travis-ci.com/repo-slug: RoadieHQ/sample-service
    buildkite.com/project-slug: roadie/test-pipe
    cloud.google.com/function-ids: projects/roadie-dev-283705/locations/europe-west1/functions/test-fn-1
    argocd/app-name: control-app
    prometheus.io/rule: memUsage|component,node_memory_Active_bytes|instance,sum by (instance) (node_cpu_seconds_total)|instance
    prometheus.io/alert: 'Excessive Memory Usage'
spec:
  type: service
  owner: Xantier
  lifecycle: experimental
  providesApis:
    - sample-service
