apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: irma-test-service
  title: Irma Test service
  description: |
    A service for testing Backstage functionality. Cofigured for Bugsnag.
  annotations:
    bugsnag.com/project-key: RoadieHQ/93b71ec25fd3e1d803af87d57cea2acd
    bugsnag.com/project-name: Test bugsnag app
    shortcut.com/project-id: '14'
    github.com/public-repository: Public
    github.com/project-slug: roadiehq/sample-service
    snyk.io/org-name: roadie
    snyk.io/project-ids: 4f195df9-5ddf-4a98-8955-bd687d220d0b    
    backstage.io/techdocs-ref: dir:.
    roadie.io/techinsights-shortcut-id: "9229"
  labels:
    label1: test-label
    label2/label2: test-label2
spec:
  type: service
  owner: irma
  lifecycle: experimental
  system: sample-system
  providesApis:
    - test-service
    
--- 
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: roadie-backstage-admin
  description: Backstage administrators
spec:
  type: team
  profile:
    displayName: Backstage Admins
    email: info@roadie.io
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: roadie-backstage-admin
  title: Backstage Admins
  description: The Backstage Admins
spec:
  type: sub-department
  profile:
    displayName: roadie-backstage-admin
    email: rroadie-backstage-admin@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  children: []
  members: [default/Irma12]
