apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-2
  description: |
    A service for testing Backstage functionality. Configured for Circle CI
    and Rollbar.
  annotations:
    circleci.com/project-slug: github/RoadieHQ/sample-service
    rollbar.com/project-slug: roadie/sample-project
    aws.com/lambda-function-name: roadie-test-load-to-elastic
    aws.com/lambda-region: eu-west-1
    backstage.io/techdocs-ref: s3://roadie-roadie-tech-docs/component/service/sample-service-2/
spec:
  type: service
  owner: dtuite
  lifecycle: experimental
  providesApis:
    - spotify
