---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
    backstage.io/kubernetes-label-selector: 'app=backstage,component=frontend'
spec:
  type: other
  lifecycle: unknown
  owner: 'user:iain@roadie.io'
