# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: dropdown-selection-demo
  title: dropdown-selection-demo
  description: Test template to see drop selections in action
spec:
  owner: roadie
  type: experiment

  parameters:
    - title: Repository for the RFC drop
      required:
        - repoUrl
      properties:
        repoUrl:
          content:
            type: string
          description: Name of repository
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - team-a
              - team-b
  steps:
    - id: sleep
      name: Sleep
      action: roadiehq:utils:sleep
      input:
        amount: 1
