site_name: Sample Service 1

nav:
  - Home: index.md
  - Local development: local-development.md
  - Feature Testing: feature-testing.md

plugins:
  - techdocs-core

# These paths are relative to the docs dorectory.
extra_css:
  - stylesheets/extra.css
