apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: modify-readme-template
  title: Modify README
  description: Appends a section and replaces a placeholder in README.md
spec:
  owner: team@example.com
  type: service

  parameters:
    - title: "Modify README"
      properties:
        appendText:
          type: string
          description: "Text to append to the README"
          default: "\n## New Section\nThis is a new section added by the scaffolder."
        replacePattern:
          type: string
          description: "Pattern to replace"
          default: "PLACEHOLDER"
        replaceWith:
          type: string
          description: "Replacement text"
          default: "Actual content"

  steps:
    - id: modify-readme
      name: Modify README
      action: custom:modify-readme
      input:
        filePath: "README.md"
        appendText: "${{ parameters.appendText }}"
        replacePattern: "${{ parameters.replacePattern }}"
        replaceWith: "${{ parameters.replaceWith }}"
