apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: test-user-a
  links:
    - url: https://roadiehq.slack.com/blahblag
      title: Slack User
      icon: chat 
spec:
  profile:
    displayName: Fname Lname
    picture: https://blah.com/fname
  memberOf:
    - engineering
