site_name: mycomponent
repo_url: https://github.com/RoadieHQ/sample-service
edit_uri: edit/main/sub-dir-documentation/docs

plugins:
  - monorepo

nav:
  - First page: index.md
  - Second page: other/other.md
